# Generated by Django 6.0.2 on 2026-02-04 08:00

import crm_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('ulid', models.CharField(default=crm_app.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.employee')),
            ],
        ),
    ]
